# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/petppy/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: script/run_new_was.sh
      timeout: 180
      runas: ec2-user
    - location: script/health_check.sh
      timeout: 180
      runas: ec2-user
    - location: script/switch.sh
      timeout: 180
      runas: ec2-user